### ISSUE TITLE
Not seeing GPU being used

### ISSUE THREAD

**Issue by ratt2581** [Collisionc/sickbeard_mp4_automator#18]
I can't seem to get it to use the GPU to handle the automation. It seems to be working in the same manner as the original mdhiggins version?

I tried with my original settings and updated for my GPU (GPU 1 is NVIDIA Quadro P600). I tried defaulting to the original settings. I tried the original settings as is and also updating to use 1 (for my GPU).

I'm assuming I'm just missing a setting, but I can't figure it out. Or maybe I'm missing how it should work, but when it runs, I don't see ffmpeg using my gpu at all. 

I tried a few different files as well.

Thank you for any help.

**Comment by Collisionc** [comment]
Can you post the [MP4] section of your autoprocess.ini file ?

**Comment by ratt2581** [comment]
Appreciate you taking the time to help me. 

So I've tried at least these 3 versions:
Attempt 1:
[MP4]
ffmpeg = C:\\Plex\\ffmpeg\\bin\\ffmpeg.exe
ffprobe = C:\\Plex\\ffmpeg\\bin\\ffprobe.exe
threads = 0
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
resolution-bitrate-restriction =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
qmin =
qmax = 
global_quality = 
maxrate =
minrate = 
bufsize =
nvenc_encoder_gpu = 1
nvenc_profile =
nvenc_preset =
nvenc_rate_control =
nvenc_temporal_aq = False
nvenc_weighted_prediction = False
nvenc_rc_lookahead =
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu = 1
nvenc_hevc_decoder_gpu = 1
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
handle_m2ts_files = False
forceconvert = False
vsync = -1
sample_rate = 
burn_in_forced_subs = False
burn_in_full_subs =  False
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = False
init_hw_device = opencl=gpu:1

**Attempt 2:**
[MP4]
ffmpeg = C:\\Plex\\ffmpeg\\bin\\ffmpeg.exe
ffprobe = C:\\Plex\\ffmpeg\\bin\\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
resolution-bitrate-restriction = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
qmin = 
qmax = 
global_quality = 
maxrate = 
minrate = 
bufsize = 
nvenc_encoder_gpu = 
nvenc_profile = 
nvenc_preset = 
nvenc_rate_control = 
nvenc_temporal_aq = False
nvenc_weighted_prediction = False
nvenc_rc_lookahead = 
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu = 
nvenc_hevc_decoder_gpu = 
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
handle_m2ts_files = False
forceconvert = False
vsync = -1
sample_rate = 
burn_in_forced_subs = False
burn_in_full_subs = False
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = False
init_hw_device = opencl=gpu:1
preopts = 
postopts = 

**Attempt 3:**
[MP4]
ffmpeg = C:\\Plex\\ffmpeg\\bin\\ffmpeg.exe
ffprobe = C:\\Plex\\ffmpeg\\bin\\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264
video-bitrate = 11500
resolution-bitrate-restriction = 
video-crf = 
video-max-width = 1920
video-profile = 
h264-max-level = 4.1
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
qmin = 
qmax = 
global_quality = 
maxrate = 
minrate = 
bufsize = 
nvenc_encoder_gpu = 1
nvenc_profile = 
nvenc_preset = 
nvenc_rate_control = 
nvenc_temporal_aq = False
nvenc_weighted_prediction = False
nvenc_rc_lookahead = 
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu = 1
nvenc_hevc_decoder_gpu = 1
ios-first-track-only = False
ios-audio-filter = dynaudnorm
ios-move-last = False
max-audio-channels = 
audio-codec = aac,ac3,mp3,dts,dca,aac
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 256
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
handle_m2ts_files = False
forceconvert = False
vsync = -1
sample_rate = 
burn_in_forced_subs = False
burn_in_full_subs = False
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = False
init_hw_device = opencl=gpu:1
preopts = 
postopts =

**Comment by Collisionc** [comment]
Set video-codec to:
video-codec = nvenc_h264, h264 

I probably need to document that, as now that I think about it, I don't know if that's mentioned anywhere in documentation. :o 

Here's a copy of my current [MP4] section if you want something to go off of.
The end result of this is that 1080p will be encoded if it's above 25 megabit average, 4k is re-encoded if it's above 50 megabit average -- of course anything other than h264 will be encoded to h264. It uses DXVA2 for decoding (nvdec is buggyish :\)
It sets the quality settings for nvenc as high as they can go, creates an AAC stereo soundtrack from anything that isn't already stereo and attempts to normalize things like loud explosions ---> spoken dialogue that is sometimes an issue when going from 5.1 to 2.1.  It also burns in non-native language subtitles as needed (Ex: Drakthorian translations to english for GoT), but it does require the original source to have those subtitles already. 

ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = nvenc_h264, h264
video-bitrate = 25000
resolution-bitrate-restriction = 1920,25000,4096,60000
video-max-width = 4096
qmin = 17
qmax = 
global_quality = 
maxrate = 1920,35000,4096,80000
minrate = 
bufsize = 1920,50000,4096,100000
nvenc_encoder_gpu = 0
nvenc_profile = 2
nvenc_preset = slow
nvenc_rate_control = vbr_hq
nvenc_temporal_aq = True
nvenc_weighted_prediction = False
nvenc_rc_lookahead = 
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu = 0
nvenc_hevc_decoder_gpu = 0
h264-max-level = 
use-qsv-decoder-with-encoder = False
enable_dxva2_gpu_decode = True
ios-audio = False
ios-first-track-only = False
max-audio-channels = 2
audio-codec = aac
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 128
subtitle-codec = 
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = False
download-subs = False
embed-subs = True
permissions = 0777
post-process = False
pix-fmt = nv12, yuv420p
quality = 
audio-filter = loudnorm
ios-audio-filter = 
sub-providers = opensubtitles, podnapisi
aac_adtstoasc = True
postopts = 
preopts = 
video-crf = 
threads = auto
handle_m2ts_files = True
forceconvert = True
vsync = -1
burn_in_forced_subs = True
sample_rate = 48000
audio-copy-original = True
ios-move-last = False
embed-only-internal-subs = True
use-hevc-qsv-decoder = False
video-profile =

The following stuff is still beta-ish, so only enable if you're ok with testing it... I've been running it for a while because I don't have any devices that support HDR and without tonemapping the HDR ---> SDR conversion looks crappy.
 
audio-first-track-of-language = True
enable_hdr_sdr_tonemapping = True
enable_opencl_hdr_sdr_tonemapping = True
init_hw_device = opencl=gpu:0
burn_in_full_subs = False

**Comment by ratt2581** [comment]
I tried your settings and still not seeing any GPU usage. I'm likely just missing something but here's the command line from task manager when it runs:
`C:\Plex\ffmpeg\bin\ffmpeg.exe `
`-fix_sub_duration `
`-vsync `
`-1 `
`-hwaccel dxva2 `
`-i E:\Downloads\filetest.x264.DTS-HD.MA.5.1\filetest.1080p.BluRay.x264.DTS-HD.MA.5.1.mkv `
`-vcodec copy `
`-map 0:0 `
`-c:a:0 aac `
`-map 0:1 `
`-disposition:a:0 default `
`-ac:a:0 2 `
`-b:a:0 256k `
`-ar:a:0 48000 `
`-filter:a:0 loudnorm `
`-metadata:s:a:0 language=eng `
`-strict experimental `
`-c:a:1 copy `
`-map 0:1 `
`-metadata:s:a:1 language=eng `
`-disposition:a:1 none `
`-c:s:0 mov_text `
`-map 0:2 `
`-disposition:s:0 default `
`-metadata:s:s:0 language=eng `
`-f mp4 `
`-threads 0 `
`-max_muxing_queue_size 2048 `
`-movflags faststart `
`-y E:\Downloads\filetest.1080p.BluRay.x264.DTS-HD.MA.5.1\filetest.1080p.BluRay.x264.DTS-HD.MA.5.1.mp4`

**Comment by Collisionc** [comment]
-vcodec copy 

This means that it is bypassing re-encoding the video stream because it already fits the requirements, ex: the average bitrate of the video stream for that .mkv file is already below the threshold that you set video-bitrate for -- or if you left video-bitrate blank.

It is re-encoding the audio stream and adding the loudnorm filter to it, which unfortunately is a very slow conversion -- Even if GPU encoding was being used in this case, loudnorm is generally the bottleneck.  

Just to test this, set:
video-bitrate = 2000

That will force the script to use nvenc to encode the videostream as long as the original source has a bitrate of 2 megabit or higher -- which it almost undoubtedly has.

**Comment by ratt2581** [comment]
nice that seemed to have been the issue. I'm seeing the GPU being used now with your script. Appreciate all the help and your time. thanks again.
